
package edu.vistas;

import edu.clases.Romboide;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * Nombre de la clase: FormuRomboide
 * Fecha: 24-05-2018
 * Version: 1.0
 * CopyRight: Andrés Alfaro
 * @author Andrés Alfaro
 */
public class FormuRomboide extends javax.swing.JInternalFrame {

   public static String k;
    public FormuRomboide() {
        k="x";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTxtL2 = new javax.swing.JTextField();
        JBtnCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JTxtL1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Romboide");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        JTxtL2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtL2KeyTyped(evt);
            }
        });

        JBtnCalcular.setText("Calcular");
        JBtnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtnCalcularMouseClicked(evt);
            }
        });

        jLabel1.setText("Altura:");

        JTxtL1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtL1KeyTyped(evt);
            }
        });

        jLabel2.setText("Base:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Area de un Romboide");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTxtL2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(28, 28, 28)
                            .addComponent(JTxtL1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBtnCalcular)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JTxtL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTxtL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBtnCalcular)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
       k=null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void JTxtL2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtL2KeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!= '.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&this.JTxtL2.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtL2KeyTyped

    private void JBtnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtnCalcularMouseClicked
        if(JTxtL1.getText().equals("") || this.JTxtL2.getText().equals("") ){
            JOptionPane.showMessageDialog(null,"Error Ingrese datos","Campos vacios",0);

        }else{
            DecimalFormat f = new DecimalFormat("#,###.00");
            Romboide obj = new Romboide();
            obj.setAltura(Double.parseDouble(this.JTxtL1.getText()));
            obj.setBase(Double.parseDouble(this.JTxtL2.getText()));
            JOptionPane.showMessageDialog(null,"Datos"+
                "\nEl Area del Romboide es:"+f.format(obj.Area())

                ,"Resultados",1);
            reseteo();

        }
    }//GEN-LAST:event_JBtnCalcularMouseClicked

    private void JTxtL1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtL1KeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&evt.getKeyChar()!= '.'){
            evt.consume();
        }
        if(evt.getKeyChar()=='.'&&this.JTxtL1.getText().contains(".")){
            evt.consume();
        }
    }//GEN-LAST:event_JTxtL1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnCalcular;
    private javax.swing.JTextField JTxtL1;
    private javax.swing.JTextField JTxtL2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
 private void reseteo() {
     this.JTxtL1.setText(null);
       this.JTxtL2.setText(null);
     
    }
}
