package edu.vistas;

import edu.clases.OperacionesCalculadora;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 * Nombre de la clase: FrmCalculadora
 * Fecha: 24-05-2018
 * Version: 1.0
 * CopyRight: Andrés Alfaro
 * @author Andrés Alfaro
 */
public class FrmCalculadora extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCalculadora
     */
    OperacionesCalculadora op=new OperacionesCalculadora();
    public FrmCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtNum1 = new javax.swing.JTextField();
        jTxtNum2 = new javax.swing.JTextField();
        jBtnSuma = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnDiv = new javax.swing.JButton();
        jBtnPo = new javax.swing.JButton();
        jBtnMul = new javax.swing.JButton();
        jBtnResta = new javax.swing.JButton();
        jBtnRa = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTxtResult = new javax.swing.JFormattedTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ejercicio 7");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel1.setText("CALCULADORA");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel2.setText("Numero 1");

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel3.setText("Numero 2");

        jTxtNum1.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jTxtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNum1ActionPerformed(evt);
            }
        });
        jTxtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNum1KeyTyped(evt);
            }
        });

        jTxtNum2.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jTxtNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNum2KeyTyped(evt);
            }
        });

        jBtnSuma.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jBtnSuma.setText("+");
        jBtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSumaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jLabel4.setText("Resultado");

        jBtnDiv.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });

        jBtnPo.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jBtnPo.setText("potencia");
        jBtnPo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPoActionPerformed(evt);
            }
        });

        jBtnMul.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jBtnMul.setText("x");
        jBtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulActionPerformed(evt);
            }
        });

        jBtnResta.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jBtnResta.setText("-");
        jBtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRestaActionPerformed(evt);
            }
        });

        jBtnRa.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jBtnRa.setText("raíz");
        jBtnRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRaActionPerformed(evt);
            }
        });

        jButton7.setText("Limpiar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTxtResult.setEditable(false);
        jTxtResult.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jTxtResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnPo)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnRa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSuma)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnResta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnMul)
                                        .addGap(14, 14, 14)
                                        .addComponent(jBtnDiv))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNum1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jTxtNum2)
                            .addComponent(jTxtResult))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSuma)
                    .addComponent(jBtnResta)
                    .addComponent(jBtnMul)
                    .addComponent(jBtnDiv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnPo)
                    .addComponent(jBtnRa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNum2KeyTyped
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.')
        {
            evt.consume();
        }
        if(evt.getKeyChar() == '.' && jTxtNum2.getText().contains("."))
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_jTxtNum2KeyTyped

    private void jBtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSumaActionPerformed
       

            llenar();
           this.jTxtResult.setText(Double.toString(op.suma()));
        
        
    }//GEN-LAST:event_jBtnSumaActionPerformed

    private void jTxtNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNum1KeyTyped
        if(!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != '.')
        {
            evt.consume();
        }
        if(evt.getKeyChar() == '.' && jTxtNum1.getText().contains("."))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtNum1KeyTyped

    private void jTxtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNum1ActionPerformed

    private void jBtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRestaActionPerformed
        
           llenar();
            this.jTxtResult.setText(Double.toString(op.resta())); 
        
        
    }//GEN-LAST:event_jBtnRestaActionPerformed

    private void jBtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulActionPerformed
       
            llenar();
            this.jTxtResult.setText(Double.toString(op.multiplicacion()));
        
        
    }//GEN-LAST:event_jBtnMulActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
       
          llenar();
          this.jTxtResult.setText(Double.toString(op.division()));  
            
        
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnPoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPoActionPerformed
        
            llenar();
            this.jTxtResult.setText(Double.toString(op.potencia())); 
         
       
    }//GEN-LAST:event_jBtnPoActionPerformed

    private void jBtnRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRaActionPerformed

            llenar();
             this.jTxtResult.setText(Double.toString(op.raiz()));
        
        
    }//GEN-LAST:event_jBtnRaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       limpiar();
    }//GEN-LAST:event_jButton7ActionPerformed
    
    public void limpiar()
    {
        this.jTxtNum1.setText("");
        this.jTxtNum2.setText("");
        this.jTxtResult.setText("");
    }
    public void llenar()
    {
       
        op.setN1(Double.parseDouble(this.jTxtNum1.getText()));
        op.setN2(Double.parseDouble(this.jTxtNum2.getText()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnMul;
    private javax.swing.JButton jBtnPo;
    private javax.swing.JButton jBtnRa;
    private javax.swing.JButton jBtnResta;
    private javax.swing.JButton jBtnSuma;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtNum1;
    private javax.swing.JTextField jTxtNum2;
    private javax.swing.JFormattedTextField jTxtResult;
    // End of variables declaration//GEN-END:variables
}
